language: julia
julia:
  - 0.4
notifications:
    email: false
script:
    - julia -e 'Pkg.clone(pwd()); Pkg.build("ControlSystems")'
    - julia -e 'Pkg.test("ControlSystems"; coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("ControlSystems")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
