language: julia
julia:
  - 1.0
  - 1
  - nightly
matrix:
  allow_failures:
  - julia: nightly
  fast_finish: true
notifications:
    email: false
addons:
  apt:
    packages:
      - xvfb
cache:
  directories:
  - $HOME/.julia/artifacts
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
  - $TESTCMD -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/JuliaControl/ControlExamplePlots.jl.git"))'
  - $TESTCMD -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
after_success:
    - julia -e 'using Pkg; import ControlSystems; cd(joinpath(dirname(pathof(ControlSystems)), "..")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
    - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
    - $TESTCMD -e 'using Pkg; Pkg.add("DSP"); Pkg.add("Documenter"); Pkg.add("GR"); Pkg.add("Plots"); Pkg.add("StaticArrays");'
    - $TESTCMD -e 'using Pkg; import ControlSystems; cd(joinpath(dirname(pathof(ControlSystems)), "..")); include(joinpath("docs", "make.jl"))'
