language: julia
julia:
  - 0.7
  - 1.0
notifications:
    email: false
before_script:
    - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/JuliaControl/ControlExamplePlots.jl", version="0.2.0"))'
after_success:
    - julia -e 'using Pkg; import ControlSystems; cd(joinpath(dirname(pathof(ControlSystems)), "..")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
    - julia -e 'using Pkg; Pkg.add("Documenter"); Pkg.add("GR"); Pkg.add("Plots"); Pkg.add("DSP")'
    - julia -e 'using Pkg; import ControlSystems; cd(joinpath(dirname(pathof(ControlSystems)), "..")); include(joinpath("docs", "make.jl"))'
