language: julia
julia:
  - 0.4
notifications:
    email: false
script:
    - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir())/ControlSystems`); Pkg.resolve()'
    - julia -e 'using ControlSystems; @assert isdefined(:ControlSystems); @assert typeof(ControlSystems) === Module'
    - julia --color=yes test/runtests.jl
